// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbxdgbpwlnmyerxyppsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNieGRnYnB3bG5teWVyeHlwcHN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODg3MjUsImV4cCI6MjA2NDQ2NDcyNX0.MfeiBir7LwXtRdC2NhsEZOo8IxXRffUdZyiv77Ltwqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);